// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0l38qPbt1hKArNnIaDNqC3ZWrnP4p1vg',
    appId: '1:32443741838:web:b90f352d61f9b5374bbbdf',
    messagingSenderId: '32443741838',
    projectId: 'iot-app-leafy-1',
    authDomain: 'iot-app-leafy-1.firebaseapp.com',
    databaseURL: 'https://iot-app-leafy-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-app-leafy-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRz-YYXBabicoXjdxCfHETiezwNGnmYsQ',
    appId: '1:32443741838:android:034e792b5c854ab84bbbdf',
    messagingSenderId: '32443741838',
    projectId: 'iot-app-leafy-1',
    databaseURL: 'https://iot-app-leafy-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-app-leafy-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOh_xDkyC1L2k9j-g2mhNplKC01A97a8Q',
    appId: '1:32443741838:ios:8d05625132ad52484bbbdf',
    messagingSenderId: '32443741838',
    projectId: 'iot-app-leafy-1',
    databaseURL: 'https://iot-app-leafy-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-app-leafy-1.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOh_xDkyC1L2k9j-g2mhNplKC01A97a8Q',
    appId: '1:32443741838:ios:8d05625132ad52484bbbdf',
    messagingSenderId: '32443741838',
    projectId: 'iot-app-leafy-1',
    databaseURL: 'https://iot-app-leafy-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-app-leafy-1.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0l38qPbt1hKArNnIaDNqC3ZWrnP4p1vg',
    appId: '1:32443741838:web:acb3ae113e2bc41c4bbbdf',
    messagingSenderId: '32443741838',
    projectId: 'iot-app-leafy-1',
    authDomain: 'iot-app-leafy-1.firebaseapp.com',
    databaseURL: 'https://iot-app-leafy-1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-app-leafy-1.firebasestorage.app',
  );
}
